spring:
  application:
    name: configdemo
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev


#build:
#  id: ${id}
#  version: ${VERSION}
#  name: ${NAME}